sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PcqCUxYrdHI7SSCkoiwXYc+jn/1arEasS3uxfdG1FjA271a48J1RD/w3QUQAQIu8jaxVo0n1b02ZE/yghZWtUuhgOn/FPkIZITnavFslHG8POWBbIMEBhQS2M+0XW3RFXZlEcfZ0LIpeUpxl59vF8ST20G1gYBcd8tyZNNbGwd1KKPRi/0jwm50El+BwbSO8m9qMyQ+C/DuTNmx2qi8n50pthvUqcBYN2gk1K8v51zri+eBLe/wcBnMi2hxIl9fUmIwvu3fGoUIiulvqV/wvGNn0xjmQ5AhI8zYTeZLTnMgJYubgcGRXf1jMh/zYIkZ4QUfcnAgrjo4Be7Wj6yFR/f8dFsl3niyZWbXMXQoHjEY2MTk62TrFpzFf3UY/JERYv3jazdVLKrhB04YTS+EOh62wDB/TpusWhUqU0Xujxa2ktM82YuiYAIqgxc0HWoRcb6kYatzTIKEB31Y6b7JsYtksX3zf/AkXHgdd7yc059EDWekdi+11YpU8QdMtXRUVLYLNbfcVvIIAeiA3YFGCQAeC819eWIynwOCGaPRWetIZBZYiNnF0rKw5vB2X915Sam12d1C3MwkRdrXX67+H4vOMScemAVQhNkIASJns8BaZ3JHpdSjgTzYX773FgwpQ/x0K5Omtdxazf0j0jwv7d/9DPAB621fse6jSMmDJXnM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/What-s-Wrong-with-the-World_1717
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy